#!/bin/bash
# invoke-rc.d tomcat7 start
# return success, even if service not installed
#
# This script creates some necessary directories and downloads models required for the nlp-extension of the gtf
#  Modify the BASEDIR as required in your system and as configured in the dme.yml configuration
#
CONFIGDIR="/etc/dfa/dme"
BASEDIR="/var/lib/dme"
INSTALLDIR="/var/dfa/webapps/dme"

if [ ! -e $CONFIGDIR ]; then
  echo "Creating DME config directory at $CONFIGDIR"
  mkdir -p $CONFIGDIR
fi

if [ ! -e $CONFIGDIR/dme.yml ]; then
  echo "Installing simple DME config directory at $CONFIGDIR/dme.yml"
  cp /var/dfa/webapps/dme/WEB-INF/classes/dme.sample_simple.yml $CONFIGDIR/dme.yml
fi

if [ ! -e $BASEDIR/grammars ]; then
  echo "Creating DME grammars directory at $BASEDIR/grammars"
  mkdir -p $BASEDIR/grammars
fi

if [ ! -e $BASEDIR/models ]; then
  echo "Creating DME models directory at $BASEDIR/models"
  mkdir -p $BASEDIR/models
fi

if [ ! -e $BASEDIR/models/openNLP-1.5-DE-sent.bin ]; then
  echo "Downloading openNLP models"
  curl -o $BASEDIR/models/openNLP-1.5-DE-sent.bin http://opennlp.sourceforge.net/models-1.5/de-sent.bin
fi

if [ ! -e $BASEDIR/models/stanford-german-corenlp-2016-10-31-models.jar ]; then
  echo "Downloading stanford models"
  curl -o $BASEDIR/models/stanford-german-corenlp-2016-10-31-models.jar https://nlp.stanford.edu/software/stanford-german-corenlp-2016-10-31-models.jar
fi

echo "--------------------------------------"
echo "DME post-installation script executed."
echo "Make sure that the web application has read/write-access to $BASEDIR/grammars and read-access to $BASEDIR/models"
echo "--------------------------------------"

exit 0